### PR TITLE
[add] Structure for platform specific extras and documentation

### PR DESCRIPTION
**Pull request by greypants**
#IN PROGRESS

@tommymarshall @mzlock I created a `gulpfile.js/extras/craft` folder for you to add stuff to.

I added the start of some Rails stuff.

Re: #203, #204

### CODE REVIEW

**Comment by mzlock** [comment]
:+1:

I'll add my little Craft plugin to this here this week.  Want me to add that directly to this branch or new branch and PR?

**Comment by greypants** [comment]
@mzlock this branch

**Comment by mzlock** [comment]
@greypants - added the plugin and some info to the README.md.  Let me know if you'd rather I move the plugin and its usage documentation into a subfolder here.

**Comment by greypants** [comment]
Closing for the moment until I get the README in there. I'll re-open then.

**Pull request closed without merging**
