### PR TITLE
Fix broken demo config.json

### PR DESCRIPTION
**Pull request by Yofamb**
Add production rev to the demo config file to stop gulp compile issue when copied over to the root.

### CODE REVIEW

**Comment by greypants** [comment]
Thanks!

**Comment by PaulyWolly** [comment]
Thanks!!

**Comment by Yofamb** [comment]
I noticed I accidentally left out a comma in my code. Should I do another pull request or can someone else quickly fix it.

**Comment by greypants** [comment]
@Yofamb thanks for catching that - I just fixed it.

**Pull request merged**
