### PR TITLE
[update] convert config.js to config.json

### LINKED ISSUE #198: Use JSON for config for cross language sharing
Just ran into this on a Rails project. I wanted to have my Rails asset path helpers read my gulpfile.js/config file, so I converted it to JSON.

**Downside:** It's not JS, so you can't have any logic in the config files (there isn't currently).
**Upside:** Easier cross-language sharing. 

Worth it?

### PR DESCRIPTION
**Pull request by greypants**
Resolves #198

### CODE REVIEW

**Comment by averyvery** [comment]
Meh, I'm not a fan of JSON as it's not really great human-readably/writeable format; it's intended more for computer use. Plus, like you say in that issue, you can't do logic or fun stuff like embedding today's date in a command. Still, if it works this is :+1:

**Comment by renestalder** [comment]
How is json less readable than a JavaScript literal object?

**Comment by averyvery** [comment]
@renestalder I would say it's _slightly_ less readable as can't you can't include any comments and you have to include additional, unnecessary quotes. But we could probably argue for weeks about relative readability and not get anywhere.

**Comment by ten1seven** [comment]
Wondering if you could have split this into a JSON file for the routes and keep the javascript config for everything else? Otherwise, it's JSON :+1:

**Comment by renestalder** [comment]
Okay, I see your point with the comments. It's also interesting that Atom.io Editor is using cson and Sublime Text using JSON Syntax with comments and .sublime-text file extension which then might be parsed to strip out the comments.

But the problem of documentation can easily be solved as examples like npm or TypeScript show.

**Comment by greypants** [comment]
@ten1seven hmm... I'm gonna think about that. Could split this out into something like `config/paths.json` and `config/tasks.js`.

**Comment by greypants** [comment]
gonna merge it for now so it works with the `/extras/rails` examples I'm adding soon. It's easy enough to change the file extension back to js if you don't need JSON and DO need js logic in there.

**Pull request merged**
