### PR TITLE
Added link to wiki page about Blendid Craft setup.

### PR DESCRIPTION
**Pull request by Bshally**
I've put together some relevant information on using Blendid with Craft that I've found throughout the repo and from some experience.

### CODE REVIEW

**Comment by greypants** [comment]
Nice! Can you re-open this against the `blendid` branch? `master` is probably getting blown away and replaced with `blendid` rather than trying to rebase or merge changes.

**Comment by greypants** [comment]
Also thats a good reminder that that Wiki exists... I forgot about it. Should probably check the content in there, huh.

**Comment by greypants** [comment]
Either way, thanks for writing that up.

**Comment by Bshally** [comment]
Sure thing! I'll make a commit on that branch again once I get a chance.

**Comment by schikulski** [comment]
Thanks for adding this @Bshally! I've run into some problems trying to set this up. Let me know in #403 if you can help me out.

**Comment by Bshally** [comment]
@schikulski Yeah, I'm running into the same issues. I'll try to sort it out if I can.

**Pull request closed without merging**
